-- Create events table if it doesn't exist
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT NOT NULL
);

-- Add columns if they don't exist (safe for existing tables)
ALTER TABLE events ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'event';
ALTER TABLE events ADD COLUMN IF NOT EXISTS date_text TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS time_text TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- Add connection to slug only if not constrained? 
-- Simplest is just to ensure it's there. 

-- Enable Row Level Security
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Public can view active events" ON events;
DROP POLICY IF EXISTS "Enable read access for all users" ON events;
DROP POLICY IF EXISTS "Enable insert for all users" ON events;
DROP POLICY IF EXISTS "Enable update for all users" ON events;
DROP POLICY IF EXISTS "Enable delete for all users" ON events;

-- Create policies
CREATE POLICY "Enable read access for all users" ON events FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON events FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON events FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON events FOR DELETE USING (true);

-- Insert sample data ONLY if the table is empty
INSERT INTO events (title, slug, type, date_text, time_text, location, image_url, description, content, is_active)
SELECT 'Çocuk Atölyesi: Resim ve Boyama', 'cocuk-atolyesi-resim-boyama', 'event', '20 Ocak 2024', '14:00 - 16:00', 'Zemin Kat - Etkinlik Alanı', 'https://images.unsplash.com/photo-1560439514-e960a3ef5019?w=800&q=80', 'Çocuklarınızın yaratıcılığını geliştirecek renkli bir atölye çalışması.', '<h2>Çocuk Atölyesi Hakkında</h2><p>Çocuklar için düzenlenen bu atölyede, uzman eğitmenler eşliğinde resim ve boyama teknikleri öğretilecektir. Tüm malzemeler AVM yönetimimiz tarafından karşılanmaktadır.</p><p>Katılım ücretsizdir ve kontenjan sınırlıdır.</p>', true
WHERE NOT EXISTS (SELECT 1 FROM events LIMIT 1);

INSERT INTO events (title, slug, type, date_text, time_text, location, image_url, description, content, is_active)
SELECT 'Kış İndirimleri Başladı!', 'kis-indirimleri-basladi', 'campaign', '15 Ocak - 15 Şubat 2024', 'Tüm Gün', 'Tüm Mağazalar', 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=800&q=80', 'Seçili mağazalarda %50 ye varan kış indirimleri sizi bekliyor.', '<h2>Kış İndirimleri</h2><p>Acity Outlet AVM de kış indirimleri başladı! Dünyaca ünlü markalarda %50 ye varan indirim fırsatlarını kaçırmayın.</p>', true
WHERE NOT EXISTS (SELECT 1 FROM events WHERE slug = 'kis-indirimleri-basladi');
Hi