-- Create Categories Table
CREATE TABLE categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Categories
INSERT INTO categories (name, slug) VALUES
('Ayakkabı & Çanta', 'ayakkabi-canta'),
('Büyük Mağazacılık', 'buyuk-magazacilik'),
('Cafe & Restaurant', 'cafe-restaurant'),
('Çocuk Giyim', 'cocuk-giyim'),
('Eğlence', 'eglence'),
('Elektronik', 'elektronik'),
('Erkek Giyim', 'erkek-giyim'),
('Ev & Dekorasyon', 'ev-dekorasyon'),
('Hizmet & Servis', 'hizmet-servis'),
('Kadın & Erkek Giyim', 'kadin-erkek-giyim'),
('Kadın Giyim', 'kadin-giyim'),
('Kitap & Kırtasiye', 'kitap-kirtasiye'),
('Market', 'market'),
('Saat & Mücevherat & Aksesuar', 'saat-mucevherat-aksesuar'),
('Sağlık & Güzellik', 'saglik-guzellik'),
('Spor', 'spor'),
('Standlar', 'standlar'),
('Yeme-İçme', 'yeme-icme'),
('Mağazalar', 'magazalar'); 
-- Added 'Mağazalar' as a general category just in case, as seen in your import list.

-- Add a category_id column to stores table for better relation (Optional but recommended for future)
-- ALTER TABLE stores ADD COLUMN category_id bigint REFERENCES categories(id);
-- For now we stick to text based 'category' column to avoid breaking current flow, 
-- but in Admin Panel we will pick from these categories and save the NAME to the store.
