-- Create event_slider table
CREATE TABLE IF NOT EXISTS event_slider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    title TEXT,
    image_url TEXT NOT NULL,
    link TEXT,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE
);

-- Enable Row Level Security
ALTER TABLE event_slider ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Enable read access for all users" ON event_slider;
DROP POLICY IF EXISTS "Enable insert for all users" ON event_slider;
DROP POLICY IF EXISTS "Enable update for all users" ON event_slider;
DROP POLICY IF EXISTS "Enable delete for all users" ON event_slider;

-- Create policies
CREATE POLICY "Enable read access for all users" ON event_slider FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON event_slider FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON event_slider FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON event_slider FOR DELETE USING (true);

-- Insert sample data
INSERT INTO event_slider (title, image_url, display_order, is_active)
SELECT 'Acity Etkinlikleri', 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&q=80', 1, true
WHERE NOT EXISTS (SELECT 1 FROM event_slider LIMIT 1);
