-- Add new stores (Do NOT drop table)
INSERT INTO stores (name, slug, category, floor, website_url) VALUES
('ADİDAS', 'adidas', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/adidas/'),
('ARCHANGEL', 'archangel', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/archangel/'),
('AYAKKABI DÜNYASI', 'ayakkabi-dunyasi', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/ayakkabi-dunyasi-2/'),
('BAMBİ', 'bambi', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/bambi/'),
('BOYNER', 'boyner', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/boyner/'),
('CEYO', 'ceyo', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/ceyo/'),
('DERIMOD', 'derimod', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/derimod/'),
('FLO', 'flo', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/flo/'),
('GREYDER', 'greyder', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/greyder/'),
('HUMMEL', 'hummel', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/hummel/'),
('INSTREET', 'instreet', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/instreet/'),
('INTERSPORT', 'intersport', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/colins/'),
('LESCON', 'lescon', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/lescon/'),
('LOS ANGELES – POLO CLUB', 'los-angeles-polo-club', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/los-angeles-polo-club/'),
('NETWORK', 'network', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/network/'),
('NIKE', 'nike', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/nike/'),
('PUMA', 'puma', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/puma/'),
('SAMSONITE', 'samsonite', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/samsonite/'),
('SKECHERS', 'skechers', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/skechers/'),
('SUPER STEP', 'super-step', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/super-step/'),
('TAMER TANCA', 'tamer-tanca', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/tamer-tanca/'),
('TERGAN', 'tergan', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/tergan/'),
('VIVENS', 'vivens', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/vivens/'),
('ABBATE', 'abbate', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/abbate/'),
('ALİ FUAT ECZANESİ', 'ali-fuat-eczanesi', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/ali-fuat-eczanesi/'),
('ALTINYILDIZ CLASSICS', 'altinyildiz-classics', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/altinyildiz-classics/'),
('ANKARA LOSTRA VE ÇİLİNGİR', 'ankara-lostra-ve-cilingir', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/ankara-lostra-ve-cilingir/'),
('ARMAĞAN', 'armagan', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/armagan/'),
('ARMİNE', 'armine', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/armine/'),
('ATASAY', 'atasay', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/atasay/'),
('ATASUN OPTİK', 'atasun-optik', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/atasun-optik/'),
('AVVA', 'avva', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/avva/'),
('BARANSU HALI', 'baransu-hali', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/baransu-hali/'),
('BATİK', 'batik', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/batik/'),
('BEKO', 'beko', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/beko/'),
('BERK MÜCEVHERAT', 'berk-mucevherat', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/berk-mucevherat/'),
('BEŞİKTAŞ JK', 'besiktas-jk', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/besiktas-jk/'),
('BEYMEN BUSINESS', 'beymen-business', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/beymen-business/'),
('BEYMEN CLUB', 'beymen-club', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/beymen-club/'),
('BOLÇİ', 'bolci', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/bolci/'),
('BOSCH', 'bosch', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/bosch/'),
('BOSS', 'boss', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/boss/'),
('CALVIN KLEIN', 'calvin-klein', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/calvin-klein/'),
('CARREFOUR-SA', 'carrefour-sa', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/carrefour-sa/'),
('CEPHANE', 'cephane', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/cephane/'),
('CHIMA', 'chima', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/chima/'),
('CITY BERBER', 'city-berber', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/city-berber/'),
('CITY GARAGE', 'city-garage', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/city-garage/'),
('CITY KADIN KUAFÖRÜ', 'city-kadin-kuaforu', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/city-kadin-kuaforu/'),
('CITY PET SHOP', 'city-pet-shop', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/city-pet-shop/'),
('COLINS', 'colins', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/colins-2/'),
('COLUMBİA', 'columbia', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/columbia/'),
('D’S DAMAT', 'ds-damat', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/ds-damat/'),
('D&R', 'dr', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/dr/'),
('DAGİ', 'dagi', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/dagi/'),
('DDIAMOND', 'ddiamond', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/ddiamond/'),
('DEFACTO', 'defacto', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/defacto/'),
('DEFNE ÇİÇEK', 'defne-cicek', 'Mağaza', 'Dış Alan', 'https://acity.com.tr/Directories/defne-cicek/'),
('DP PARFÜM', 'dp-parfum', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/dp-parfum/'),
('EKOL', 'ekol', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/ekol/'),
('ELİS GÜMÜŞ', 'elis-gumus', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/elis-gumus/'),
('ENGLISH HOME', 'english-home', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/english-home/'),
('FENERIUM', 'fenerium', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/fenerium/'),
('GANT', 'gant', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/gant/'),
('GAP', 'gap', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/gap/'),
('GLAM LIFE GÜZELLİK SALONU', 'glam-life-guzellik-salonu', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/glam-life-guzellik-salonu/'),
('GOLD MAGAZİN', 'gold-magazin', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/gold-magazin/'),
('GRATIS', 'gratis', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/gratis/'),
('GS STORE', 'gs-store', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/gs-store/'),
('GUESS', 'guess', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/guess/'),
('GUSTO', 'gusto', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/knitss/'),
('HELLO SWEETIE (HARİBO)', 'hello-sweetie-haribo', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/hello-sweetie-haribo/'),
('HİLAL TERZİ', 'hilal-terzi', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/hilal-terzi/'),
('HİSAR', 'hisar', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/hisar/'),
('I LIKE AKSESUAR', 'i-like-aksesuar', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/i-like-aksesuar/'),
('İGS', 'igs', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/igs/'),
('JACK&JONES', 'jackjones', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/jackjones/'),
('JEPUBLIC', 'jepublic', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/jepublic/'),
('JIMMY KEY', 'jimmy-key', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/jimmy-key/'),
('JOMA EXUMA', 'joma-exuma', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/joma-exuma/'),
('JOURNEY', 'journey', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/journey/'),
('KARACA 1917', 'karaca-1917', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/karaca-1917/'),
('KARACA ZÜCCACİYE', 'karaca-zuccaciye', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/karaca/'),
('KİĞILI', 'kigili', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/kigili/'),
('KNıTSS', 'knitss', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/knitss-2/'),
('KOÇTAŞ', 'koctas', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/koctas/'),
('KORKMAZ', 'korkmaz', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/korkmaz/'),
('KOTON', 'koton', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/koton/'),
('LC WAIKIKI', 'lc-waikiki', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/lc-waikiki/'),
('LEE COOPER', 'lee-cooper', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/lee-cooper/'),
('LEVIS', 'levis', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/levis/'),
('LG ELEKTRONİK', 'lg-elektronik', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/lg-elektronik/'),
('LUFIAN', 'lufian', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/lufian/'),
('MAD PARFUMEUR', 'mad-parfumeur', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/mad-parfumeur/'),
('MADAME COCO', 'madame-coco', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/madame-coco/'),
('MADAME MOSS', 'madame-moss', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/madame-moss/'),
('MARKS SPENCER', 'marks-spencer', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/marks-spencer/'),
('MAVİ', 'mavi', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/mavi/'),
('MCOVER', 'mcover', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/mcover/'),
('MODA İLGİ', 'moda-ilgi', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/moda-ilgi/'),
('MY OPTİCAL OPTİK', 'my-optical-optik', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/my-optical-optik/'),
('NAUTICA', 'nautica', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/nautica/'),
('PALERMO', 'palermo', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/tugra-tesbih/'),
('PENTİ', 'penti', 'Mağaza', 'Kat-2
Zemin Kat', 'https://acity.com.tr/Directories/penti/'),
('PIERRE CARDIN', 'pierre-cardin', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/pierre-cardin/'),
('POİNT OPTİK', 'point-optik', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/point-optik/'),
('PRESTIGE ACCESORIES', 'prestige-accesories', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/prestige-accesories/'),
('RENNA XXL', 'renna-xxl', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/renna-xxl/'),
('RİVA BALO VE NİKAH SALONU', 'riva-balo-ve-nikah-salonu', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/riva-balo-ve-nikah-salonu/'),
('ROSSMAN', 'rossman', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/rossman/'),
('SAAT & SAAT', 'saat-saat', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/saat-saat/'),
('SAMSUNG', 'samsung', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/samsung/'),
('SAMSUNG MOBILE', 'samsung-mobile', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/samsung-mobile/'),
('SARAR', 'sarar', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/sarar/'),
('SENSETIVE KURU TEMİZLEME', 'sensetive-kuru-temizleme', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/sensetive-kuru-temizleme/'),
('SERRANO FASHION', 'serrano-fashion', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/serrano-fashion/'),
('SETRMS', 'setrms', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/setrms/'),
('SIEMENS', 'siemens', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/siemens/'),
('SİTARE', 'sitare', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/sitare/'),
('SUWEN', 'suwen', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/suwen/'),
('TEFAL', 'tefal', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/tefal/'),
('TIFFANY & TOMATO', 'tiffany-tomato', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/tiffany-tomato/'),
('TOBACCO SHOP', 'tobacco-shop', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/tobacco-shop/'),
('TOMMY HILFIGER', 'tommy-hilfiger', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/tommy-hilfiger/'),
('TTO SHOP', 'tto-shop', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/tto-shop/'),
('TUDORS', 'tudors', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/tudors/'),
('TUĞBA', 'tugba', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/tugba/'),
('TUĞRA TESBİH', 'tugra-tesbih', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/tugra-tesbih-2/'),
('TÜRK TELEKOM', 'turk-telekom', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/turk-telekom/'),
('TURKCELL', 'turkcell', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/turkcell/'),
('TURKISH AIRLINES', 'turkish-airlines', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/jollytur/'),
('UNION TAKI', 'union-taki', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/union-taki/'),
('US POLO', 'us-polo', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/us-polo/'),
('USTA MAKASLAR', 'usta-makaslar', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/usta-makaslar/'),
('VDR', 'vdr', 'Mağaza', 'Kat 1', 'https://acity.com.tr/Directories/vdr/'),
('VESTEL', 'vestel', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/vestel/'),
('WATSONS', 'watsons', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/watsons/'),
('YÜKSELEN SAAT', 'yukselen-saat', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/yukselen-saat/'),
('YVES ROCHER', 'yves-rocher', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/yves-rocher/'),
('ADELAND ÇOCUK OYUN EVİ', 'adeland-cocuk-oyun-evi', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/adeland-cocuk-oyun-evi/'),
('ARENA TRAMBOLİN', 'arena-trambolin', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/arena-trambolin/'),
('CİNEVİZYON', 'cinevizyon', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/cinevizyon/'),
('EĞLENCE ADASI', 'eglence-adasi', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/eglence-adasi/'),
('EZEL BALON EVİ', 'ezel-balon-evi', 'Mağaza', 'Kat 2', 'https://acity.com.tr/Directories/ezel-balon-evi/'),
('KUMPANYA KUM HAVUZU', 'kumpanya-kum-havuzu', 'Mağaza', 'Kat-2', 'https://acity.com.tr/Directories/kumpanya-kum-havuzu/'),
('TOYZZ SHOP', 'toyzz-shop', 'Mağaza', 'Kat -1', 'https://acity.com.tr/Directories/toyzz-shop/'),
('D’S  DAMAT', 'ds-damat', 'Mağaza', 'Zemin Kat', 'https://acity.com.tr/Directories/ds-damat/') ON CONFLICT (slug) DO NOTHING;