-- Drop existing table if exists (Be careful with this in production!)
DROP TABLE IF EXISTS stores;

-- Create stores table
CREATE TABLE stores (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text unique not null,
    category text,
    floor text,
    phone text,
    logo_url text,
    description text,
    website_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert data
INSERT INTO stores (name, slug, category, floor, website_url) VALUES
('COFFE DI TOEE', 'coffe-di-toee', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/coffee-di-toe/'),
('STARBUCKS', 'starbucks', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/starbucks/'),
('YAPRAK DÖNERCİSİ', 'yaprak-donercisi', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/yaprak-donercisi/'),
('TAVUK DÜNYASI', 'tavuk-dunyasi', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/tavuk-dunyasi/'),
('PİDELİ', 'pideli', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/pideli/'),
('LAHMACUN MOLA', 'lahmacun-mola', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/lahmacun-mola/'),
('MC DONALDS', 'mc-donalds', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/mc-donalds/'),
('HD İSKENDER', 'hd-iskender', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/hd-iskender/'),
('ÇAY TAZE', 'cay-taze', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/cay-taze/'),
('BURSA KEBAP EVİ', 'bursa-kebap-evi', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/bursa-kebap-evi/'),
('ARDEN FC', 'arden-fc', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/arden-fc/'),
('KAHVE DÜNYASI', 'kahve-dunyasi', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/kahve-dunyasi/'),
('SİMİTÇİ DÜNYASI', 'simitci-dunyasi', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/simitci-dunyasi/'),
('YEMENLİ KAHVECİ', 'yemenli-kahveci', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/yemenli-kahveci/'),
('TERRA PİZZA', 'terra-pizza', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/terra-pizza/'),
('SBARRO', 'sbarro', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/sbarro/'),
('ÖKÜZ BURGER', 'okuz-burger', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/okuz-burger/'),
('MEYWA WAFFLE', 'meywa-waffle', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/meywa-waffle/'),
('KAYSERİ MUTFAĞI', 'kayseri-mutfagi', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/kayseri-mutfagi/'),
('BURSA ŞAHANE İSKENDER', 'bursa-sahane-iskender', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/bursa-sahane-iskender-2/'),
('DÜRÜMLE', 'durumle', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/bursa-sahane-iskender/'),
('BURGER KING', 'burger-king', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/burger-king/'),
('MADO', 'mado', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/mado/'),
('ARABICA', 'arabica', 'Yeme-İçme', 'Zemin Kat', 'https://acity.com.tr/Directories/arabica/'),
('BIG BUBBLE TEA', 'big-bubble-tea', 'Yeme-İçme', 'Kat 2', 'https://acity.com.tr/Directories/big-bubble-tea/');