const fs = require('fs');
const path = require('path');

const jsonPath = path.join(__dirname, '../acity_magazalar_final.json');
const outputPath = path.join(__dirname, '../SUPABASE_STORES.sql');

const stores = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));

function slugify(text) {
    return text
        .toString()
        .toLowerCase()
        .replace(/\s+/g, '-')           // Replace spaces with -
        .replace(/[^\w\-üğıişçö]+/g, '') // Remove all non-word chars (preserving Turkish chars if possible or just map them)
        .replace(/\-\-+/g, '-')         // Replace multiple - with single -
        .replace(/^-+/, '')             // Trim - from start of text
        .replace(/-+$/, '');            // Trim - from end of text
}

// Better slugify for Turkish characters
function turklishSlugify(text) {
    const trMap = {
        'ç': 'c', 'ğ': 'g', 'ı': 'i', 'i': 'i', 'ö': 'o', 'ş': 's', 'ü': 'u',
        'Ç': 'C', 'Ğ': 'G', 'I': 'I', 'İ': 'I', 'Ö': 'O', 'Ş': 'S', 'Ü': 'U'
    };

    let slug = text.replace(/[çğıiöşüÇĞIİÖŞÜ]/g, (char) => trMap[char] || char);
    return slug.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-');
}

let sql = `-- Drop existing table if exists (Be careful with this in production!)
DROP TABLE IF EXISTS stores;

-- Create stores table
CREATE TABLE stores (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text unique not null,
    category text,
    floor text,
    phone text,
    logo_url text,
    description text,
    website_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert data
INSERT INTO stores (name, slug, category, floor, website_url) VALUES
`;

const values = stores.map(store => {
    const slug = turklishSlugify(store.name);
    // Escape single quotes in name (e.g. McDonald's)
    const name = store.name.replace(/'/g, "''");
    const floor = store.floor;
    const category = store.category;
    const link = store.link; // We'll put original link in website_url for now

    return `('${name}', '${slug}', '${category}', '${floor}', '${link}')`;
});

sql += values.join(',\n') + ';';

fs.writeFileSync(outputPath, sql);
console.log('SQL generated at ' + outputPath);
